baseURL = "https://www.jit-y.net/"
languageCode = "ja"
title = "jit-y"
pygmentsCodefences = true
pygmentsStyle = "native"
pygmentsOptions = "nobackground=true"

[permalinks]
archives = "/archives/:filename"
