version: 2.0
jobs:
  deploy:
    working_directory: ~/workspace
    docker:
      - image: golang:1.9.2-alpine
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            apk update
            apk add --no-cache git=2.13.5-r0 py-pip=9.0.1-r1
            pip install awscli==1.11.120
            aws configure set preview.cloudfront true
      - run:
          name: Install hugo
          command: go get -v github.com/gohugoio/hugo
      - run:
          name: Build hugo
          command: hugo
      - run:
          name: Deploy to S3 and delete cloudfront cache
          command: |
            aws s3 sync --acl public-read --exact-timestamps public/ s3://jit-y/ --delete
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
